CREATE TABLE sys_usuario (
  ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NOME VARCHAR(50) NOT NULL,
  USUARIO VARCHAR(20) NOT NULL,
  SENHA VARCHAR(20)
);

INSERT INTO sys_usuario(ID,NOME,USUARIO,SENHA) VALUES(NULL,'FELIPE SOUZA CERQUEIRA DOS SANTOS','felipe','falcao998);